import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync } from 'fs';

const PLUGIN_DIR = "D:/OneDrive/Obsidian Vault/MyVault/.obsidian/plugins/obs-note-to-snippet";

const copyFilesPlugin = {
	name: "copy-files",
	setup(build) {
		build.onEnd(() => {
			copyFileSync("styles.css", `${PLUGIN_DIR}/styles.css`);
			copyFileSync("manifest.json", `${PLUGIN_DIR}/manifest.json`);
		});
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "D:/OneDrive/Obsidian Vault/MyVault/.obsidian/plugins/obs-note-to-snippet/main.js",
	minify: prod,
	plugins: [copyFilesPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
